apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: leovs09/asqa-answer
  newTag: 0.2.4
- name: leovs09/asqa-answer2gql
  newTag: 0.1.1
- name: leovs09/asqa-core
  newTag: 0.3.3
- name: leovs09/asqa-search
  newTag: 0.6.0
- name: leovs09/asqa-telegram-integration
  newTag: 0.1.1

patchesStrategicMerge:
- nodeSelectors.yaml

resources:
- ../../base
