apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  labels:
    tier: database
    solution: asqa
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: asqa
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: message.from.user.v1
  labels:
    strimzi.io/cluster: "kafka"
    solution: asqa
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: message.to.user.v1
  labels:
    strimzi.io/cluster: "kafka"
    solution: asqa
spec:
  partitions: 1 # telegram integration not support scaling
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: kafka2mongodb-sink-connector
  labels:
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: org.apache.kafka.connect.file.MongoSinkConnector
  tasksMax: 2
  config:
    connection:
      uri: mongodb://root:mongodb-asqa-password@mongodb:27017/kafka?authSource=admin
    collection: chats-messages
    topics: 
      - message.from.user.v1
      - message.to.user.v1