# Default configuration values, real values will be set from enviroment
SERVER_PORT: 8894
GRAPHQL_DEBUG: true
APP_VERSION: "0.4.0"
MONGODB_URL: "mongodb://root:example@mongo:27017/"
DEBUG_LOG: true
CACHE_FOLDER: '/cache'
INDEX_FILENAME: 'scann262144x1_wiki40b_num_17553713_brute_force.index'
TOKENIZER_FILENAME: 'tokenizer'
EMBEDER_FILENAME: 'embeder'