apiVersion: v1
kind: PersistentVolume
metadata:
  name: search-models-cache-volume
  labels:
    type: cache
    solution: asqa
    app.kubernetes.io/name: search
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: asqa
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volume/asqa/search"
