apiVersion: v1
kind: PersistentVolume
metadata:
  name: search-models-cache-volume
  labels:
    type: cache
    solution: asqa
    app.kubernetes.io/name: search
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: asqa
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-models-cache-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    tier: backend
    solution: asqa
    app.kubernetes.io/name: search
    app.kubernetes.io/version: "%VERSION%"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: asqa
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: search
      tier: backend
      solution: asqa
  template:
    metadata:
      labels:
        app: search
        tier: backend
        solution: asqa
    spec:
      volumes:
      - name: search-models-cache-storage
        persistentVolumeClaim:
          claimName: search-models-cache-claim
      containers:
      - image: 449682673987.dkr.ecr.eu-central-1.amazonaws.com/asqa-search:%VERSION%
        name: asqa-search
        imagePullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 2
            memory: 6G
          limits:
            cpu: 6
            memory: 10G
          
        ports:
        - name: main-port
          containerPort: 80
        
        volumeMounts:
        - mountPath: "/cache"
          name: search-models-cache-storage
        
        env:
        - name: SERVER_PORT
          value: '80'
        - name: GRAPHQL_DEBUG
          value: 'false'
        - name: MONGODB_URL
          value: mongodb://root:mongodb-asqa-password@mongodb:27017/
        - name: DEBUG_LOG
          value: 'false'
        - name: CACHE_FOLDER
          value: '/cache'
        - name: INDEX_FILENAME
          value: 'scann262144x1_wiki40b_num_17553713_brute_force.index'
        - name: TOKENIZER_FILENAME
          value: 'tokenizer'
        - name: EMBEDER_FILENAME
          value: 'embeder'
        
        livenessProbe:
          httpGet:
            path: /is-live
            port: main-port
      
        readinessProbe:
          httpGet:
            path: /is-ready
            port: main-port

        startupProbe:
          httpGet:
            path: /is-ready
            port: main-port
          failureThreshold: 30
          periodSeconds: 20 # 30 * 20 = 600s = 10m for start
      imagePullSecrets:
      - name: eu-central-1-ecr-registry # aws
---      
apiVersion: v1
kind: Service
metadata:
  name: search
  labels:
    app: search
    tier: backend
    solution: asqa
    app.kubernetes.io/name: search
    app.kubernetes.io/version: "%VERSION%"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: asqa
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: search
    tier: backend
    solution: asqa
