name: Bump search version
on:
  pull_request:
    branches:
      - main
    types:
    - opened
    - labeled
    - unlabeled
    paths:
      - "search/**"

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Resolve bump label
      id: bump
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: major,minor,patch
    - name: Set version variables
      run: |
        VER=$(grep VERSION search/settings.yaml | cut -d '"' -f 2)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Bump version
      id: next_version
      uses: zwaldowski/semver-release-action@v2
      with:
        bump: ${{ steps.bump.outputs.match }}
        prefix: search_v
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
      env:
        VERSION: ${{ env.VERSION }}
    - name: Save new version
      run: |-
        cd search
        sed -i -E 's/APP_VERSION: "(.*)"/APP_VERSION: "${{ steps.next_version.outputs.version }}"/g' settings.yaml
    - name: Push changes
      uses: EndBug/add-and-commit@v7
      with: 
        default_author: github_actions
        message: 'search_v${{ steps.next_version.outputs.version }}'
        tag: 'search_v${{ steps.next_version.outputs.version }} --force'
