name: Bump search version
on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "search/**"

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Resolve bump label
      id: bump
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: major,minor,patch
    - name: Bump version
      uses: zwaldowski/semver-release-action@v1
      with:
        bump: ${{ steps.bump.outputs.match }}
        profix: search_v
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Save new version
      run: |-
        cd search
        sed -i -E 's/APP_VERSION: "(.*)"/APP_VERSION: "${{ steps.next_version.outputs.version }}"/g' settings.yaml
    - run: |
        git add .
        git commit -m "search_v${{ steps.next_version.outputs.version }}"
        git push
        echo ::set-output name=sha::$(git rev-parse HEAD)