name: Release checks
on:
  pull_request:
    branches:
    - master
    types:
    - opened
    - labeled
    - unlabeled
jobs:
  includes_version_bump:
    name: Labels include one of 'major', 'minor', or 'patch'
    runs-on: ubuntu-latest
    steps:
    - name: Check PR labels
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: major,minor,patch