# This workflow will build and push a new container image

on:
  push:
    branches:
      - main
    paths:
      - "answer/production/**"

name: Push Answer Production Image to Docker Hub

jobs:
  push:
    name: Push Answer Production image
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Read version from pack.settings.yaml and set version variables
      run: |
        VER=$(grep VERSION answer/pack.settings.yaml | cut -d '"' -f 2)
        echo "VERSION=$VER" >> $GITHUB_ENV

    - name: Build, tag, and push image
      id: build-image
      env:
        REGISTRY: leovs09
        REPOSITORY: asqa-answer
        IMAGE_TAG: ${{ env.VERSION }}
      run: |
        # Build a docker container and push.
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./answer/production
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"
